### ISSUE TITLE
Plane: Flight timer on OSD (MAX7456) displays random digits after some time

### ISSUE THREAD

**Issue by giacomo892** [ArduPilot/ardupilot#12948]
After 67:07 minutes of flight the flight timer duration on the OSD started to show random values , using lot of space and covering other symbols as you can see from the current screenshot:

![image](https://user-images.githubusercontent.com/20860004/69948426-e92cfb80-14ef-11ea-85c9-6d9e2ed1d916.png)

Video showing the issue:

[2019-12-02 10.38.19.mp4.zip](https://github.com/ArduPilot/ardupilot/files/3910507/2019-12-02.10.38.19.mp4.zip)

**Version**
Running Master at fba5732292 compiled on OSX using the suggested compiler from brew.

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[X] Plane
[  ] Rover
[  ] Submarine

**Hardware type**
Matek F405 STD (ChibiOS) 

**Logs**
Have been sent directly to @tridge for privacy reasons.

**Comment by tridge** [comment]
should be fixed by #12949

**Comment by giacomo892** [comment]
@tridge not fixed. It happened again on my setup running latest master. This time it happened at 68.27 minutes of flying so around the same of the previous flight. You should get / already got some useful data to further debug the issue. Thanks

**Comment by peterbarker** [comment]
@giacomo892 are you able to test https://github.com/ArduPilot/ardupilot/pull/13001 ?

That roughly-an-hour time is quite a tell - 16-bit milliseconds wraps at that point.

**Comment by giacomo892** [comment]
@peterbarker 
It's very unlikely for that to be the issue, since I have multiple reports from a friend who has flown much more than me and had no issues in the timer.

This time I've noticed that once this happened the messages showed "mission 3 WP" briefly but I was in FBWA!

Then I landed.. tried to arm again and  I was getting prearm internal errors 0x8000

**Comment by peterbarker** [comment]
@giacomo892 OK, before you landed you should have been being screamed at - internal errors are very bad.

Does tridge have the logs for that internal-error flight?

**Comment by tridge** [comment]
The log is in AP_Stat
2019-11-30 22:23:13.07: PARM {TimeUS : 4158508040, Name : STAT_FLTTIME, Value : 5763.0}
2019-11-30 22:23:43.07: PARM {TimeUS : 4188510464, Name : STAT_FLTTIME, Value : 5793.0}
2019-11-30 22:24:14.07: PARM {TimeUS : 4219507674, Name : STAT_FLTTIME, Value : 5824.0}
2019-11-30 22:24:45.07: PARM {TimeUS : 4250508090, Name : STAT_FLTTIME, Value : 5855.0}
2019-11-30 22:25:16.07: PARM {TimeUS : 4281507393, Name : STAT_FLTTIME, Value : 5886.0}
2019-11-30 22:25:46.15: PARM {TimeUS : 4311586762, Name : STAT_FLTTIME, Value : 1979985792.0}
2019-11-30 22:26:17.15: PARM {TimeUS : 4342586833, Name : STAT_FLTTIME, Value : -17173922.0}
2019-11-30 22:26:47.16: PARM {TimeUS : 4372598201, Name : STAT_FLTTIME, Value : -841807616.0}

It is clear that STAT_FLTTIME goes crazy within 30s of 5886.

**Comment by giacomo892** [comment]
@tridge do you have an idea why message box on the OSD displayed again "mission 3 WP"  ? 
It had displayed it after the plane was heading to WP3 after AUTO takeoff just before I switched to CRUISE and continued my flight normally till the point the timer went crazy and displayed that message briefly again.

**Comment by tridge** [comment]
I think it is because MatekF405-STD user a 16 bit timer

**Comment by tridge** [comment]
it is clearly wrap of 32 bit micros boot time:
2019-11-30 22:25:16.07: PARM {TimeUS : 4281507393, Name : STAT_FLTTIME, Value : 5886.0}
2019-11-30 22:25:46.15: PARM {TimeUS : 4311586762, Name : STAT_FLTTIME, Value : 1979985792.0}

4281507393 0xFF329E41 037714517101
4311586762 0x100FD97CA 040077313712

**Comment by tridge** [comment]
I've reproduced the issue, still working on a fix
