### ISSUE TITLE
Plane: integrate AP_LandingGear's new OPTIONS parameters

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#13665]
This PR https://github.com/ArduPilot/ardupilot/pull/13638 enhances the AP_LandingGear library by adding a new OPTIONS parameter so users can specify if they would like the landing gear to automatically retract after takeoff and/or deplaoy during landing.  We should integrate this into Plane and QuadPlane as well.

**Comment by rmackay9** [comment]
I had a serious look at trying to implement this for plane but it's beyond me.  One change that I think would be good is to add these lines to the bottom of [Plane::complete_auto_takeoff()](https://github.com/ArduPilot/ardupilot/blob/master/ArduPlane/takeoff.cpp#L269):

>    // optionally retract landing gear
>    g2.landing_gear.retract_after_takeoff();

**Comment by tridge** [comment]
fixed in #13953

**Comment by pompecukor** [comment]
@tridge @rmackay9 

It is still not working, testing with options set to 0 or to only land. And it would still retract on takeoff.

In the below picture retract is set to 65m, Transition is set to 30m. Option is set to 0.
As you can see it still retracts.

![image](https://user-images.githubusercontent.com/31744367/79212167-81949e80-7e47-11ea-9766-6cdce3a27c04.png)
