### ISSUE TITLE
arming error if a enabled sensor is not found

### ISSUE THREAD

**Issue by tridge** [ArduPilot/ardupilot#1721]

**Comment by gmorph** [comment]
Need to add a check that if they have configured an  airspeed sensor but it didn't find one.   The same for Rangefinder and compass.
Need to check that a message appears on the console when arming fails which clearly indicates what has failed.
Also need to check that the LED flashes and buzzer sounds in a consistent way that copter handles this.
Needs to check if you have more then one type of the same sensor they are reporting - so multiple IMUs (Pixhawk) do a check - do in the same way Copter handles this.

**Comment by tridge** [comment]
done for airspeed and compass
not done for rangefinder yet

**Comment by magicrub** [comment]
done for GPS2

**Comment by rmackay9** [comment]
Still not done for range finders yet I'm afraid.

@Naterater, Thanks for the big issue list review by the way!

**Comment by peterbarker** [comment]
@WickedShell did rangefinders.  All done.
