### ISSUE TITLE
Picture trigger should be decoupled from GPS updates

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#6378]
This is an edge case but at the moment "do_take_picture" is triggered from the "Copter::update_GPS" function but it's theoretically possible that we are using a different position estimate source beside the GPS (i.e. visual odometry).

**Comment by OXINARF** [comment]
@rmackay9 I've updated the title as this affects all vehicles. Feel free to change it again if you don't find it clear enough.

**Comment by 7princekumar** [comment]
I would like to work on it but have no clue . I am new to open source contribution. I need your help to solve this.

**Comment by WickedShell** [comment]
Done in #14804

**Comment by rmackay9** [comment]
Except that this line still exists meaning the camera trigger still won't work without a GPS. https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Camera/AP_Camera.cpp#L344

**Comment by WickedShell** [comment]
Hmm, yeah okay, I yield there, that should probably be addressed as well :)
